version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  logger:
    image: ${DOCKERHUB_USERNAME}/logger:latest
    ports:
      - "6000:6000"
    volumes:
      - ./logger/logs:/app/logs

  backend:
    image: ${DOCKERHUB_USERNAME}/backend:latest
    depends_on:
      - db
      - logger
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      LOGGER_URL: ${LOGGER_URL}
    volumes:
      - ./backend:/app

  frontend:
    image: ${DOCKERHUB_USERNAME}/frontend:latest
    depends_on:
      - backend
    ports:
      - "8080:8080"
    environment:
      BACKEND_URL: ${BACKEND_URL}

volumes:
  db-data:
